[workspace]
authors = ["electronics10 <electronicstenio@gmail.com>"]
channels = ["conda-forge"]
name = "pet-correction"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
parallelproj = ">=1.10.2,<2"
cupy = ">=14.1.0,<15"
cuda-version = "12.*"
matplotlib = ">=3.10.9,<4"
scikit-image = ">=0.26.0,<0.27"
pandas = ">=3.0.3,<4"

[system-requirements]
cuda = "12"
